import { defineConfig } from "oxfmt";

export default defineConfig({
	ignorePatterns: [".*", "example_files"],
	arrowParens: "avoid",
	bracketSameLine: false,
	bracketSpacing: true,
	singleQuote: false,
	trailingComma: "all",
	printWidth: 80,
	endOfLine: "lf",
	semi: true,
	useTabs: true,
	tabWidth: 2,
	proseWrap: "preserve",
	htmlWhitespaceSensitivity: "css",
	sortPackageJson: false,
	sortImports: {
		newlinesBetween: false,
		groups: [
			"side_effect-builtin",
			"side_effect-external",
			"side_effect-type",
			"side_effect-import",
			{ newlinesBetween: true },
			"value-builtin",
			"value-external",
			"type-import",
			{ newlinesBetween: true },
			["type-internal", "value-internal"],
			["type-parent", "value-parent"],
			["type-sibling", "value-sibling"],
			["type-index", "value-index"],
			{ newlinesBetween: true },
			"side_effect-internal",
			"side_effect-parent",
			"side_effect-sibling",
			"side_effect-index",
			{ newlinesBetween: true },
			"unknown",
		],
	},
});
