import { defineConfig } from "oxlint";

export default defineConfig({
	ignorePatterns: ["node_modules", "out"],
	plugins: ["oxc", "unicorn", "import", "eslint", "promise", "typescript"],
	categories: {
		perf: "warn",
		pedantic: "warn",
		style: "warn",
		nursery: "warn",
		suspicious: "warn",
	},
	options: { typeAware: true, reportUnusedDisableDirectives: "warn" },
	jsPlugins: ["eslint-plugin-import-zod"],
	rules: {
		"no-void": ["error", { allowAsStatement: true }],
		"func-style": ["error", "declaration", { allowArrowFunctions: true }],
		"arrow-body-style": ["warn", "as-needed"],
		"no-unused-vars": "off",
		"no-underscore-dangle": ["warn", { allow: ["_default"] }],
		"no-console": "warn",
		eqeqeq: ["error", "always", { null: "ignore" }],
		"no-param-reassign": "warn",
		"no-empty": "error",
		"no-var": "error",

		"import-zod/prefer-zod-namespace": "error",

		"max-lines-per-function": "off",
		"max-lines": "off",
		"no-warning-comments": "off",
		"sort-imports": "off",
		"sort-keys": "off",
		"id-length": "off",
		"capitalized-comments": "off",
		"no-ternary": "off",
		"no-implicit-coercion": "off",
		"max-params": "off",
		curly: "off",
		"new-cap": "off",
		"max-statements": "off",
		"no-magic-numbers": "off",
		"no-nested-ternary": "off",
		"no-shadow": "off",
		"no-inline-comments": "off",
		"no-map-spread": "off",
		"no-negated-condition": "off",
		"prefer-await-to-callbacks": "off",
		"init-declarations": "off",
		"require-unicode-regexp": "off",
		"no-accumulating-spread": "off",
		"func-names": "off",
		"max-classes-per-file": "off",
		"no-promise-executor-return": "off",

		"unicorn/prefer-modern-math-apis": "warn",
		"unicorn/no-abusive-eslint-disable": "warn",
		"unicorn/explicit-length-check": "off",
		"unicorn/no-static-only-class": "off",
		"unicorn/prefer-array-index-of": "off",
		"unicorn/no-await-expression-member": "off",
		"unicorn/no-null": "off",
		"unicorn/no-nested-ternary": "off",
		"unicorn/filename-case": "off",
		"unicorn/prefer-global-this": "off",
		"unicorn/no-negated-condition": "off",
		"unicorn/no-array-callback-reference": "off",

		"import/no-cycle": "error",
		"import/group-exports": "off",
		"import/no-named-export": "off",
		"import/exports-last": "off",
		"import/consistent-type-specifier-style": "off",
		"import/no-nodejs-modules": "off",
		"import/no-namespace": "off",
		"import/no-named-as-default-member": "off",
		"import/no-unassigned-import": "off",
		"import/prefer-default-export": "off",
		"import/max-dependencies": "off",
		"import/no-anonymous-default-export": "off",

		"promise/avoid-new": "off",
		"promise/prefer-await-to-then": "off",
		"promise/always-return": "off",

		"typescript/no-unused-vars": "error",
		"typescript/no-unnecessary-condition": "warn",
		"typescript/array-type": ["warn", { default: "array" }],
		"typescript/no-deprecated": "warn",
		"typescript/ban-ts-comment": ["error", { minimumDescriptionLength: 5 }],
		"typescript/only-throw-error": ["error", { allow: [] }],
		// TODO: "typescript/naming-convention": "warn",
		"typescript/no-misused-promises": [
			"error",
			{
				checksVoidReturn: {
					attributes: false,
					arguments: false,
					properties: false,
				},
			},
		],
		"typescript/restrict-plus-operands": [
			"error",
			{
				allowAny: false,
				allowBoolean: false,
				allowNullish: false,
				allowNumberAndString: false,
				allowRegExp: false,
			},
		],
		"typescript/restrict-template-expressions": [
			"error",
			{
				allow: [{ name: ["Error", "URL", "URLSearchParams"], from: "lib" }],
				allowAny: false,
				allowBoolean: false,
				allowNever: false,
				allowNullish: false,
				allowNumber: true,
				allowRegExp: false,
			},
		],
		"typescript/consistent-type-definitions": ["error", "interface"],
		"typescript/consistent-type-imports": [
			"error",
			{ fixStyle: "inline-type-imports", disallowTypeAnnotations: false },
		],
		"typescript/switch-exhaustiveness-check": [
			"error",
			{
				allowDefaultCaseForExhaustiveSwitch: false,
				considerDefaultExhaustiveForUnions: true,
			},
		],
		"typescript/no-explicit-any": "error",

		"typescript/prefer-readonly-parameter-types": "off",
		"typescript/no-confusing-void-expression": "off",
		"typescript/strict-boolean-expressions": "off",
		"typescript/strict-void-return": "off",
		"typescript/prefer-nullish-coalescing": "off",
		"typescript/return-await": "error",
		"typescript/consistent-return": "off",
		"typescript/no-unsafe-type-assertion": "off",
		"typescript/no-extraneous-class": "off",
		"typescript/prefer-enum-initializers": "off",
		"typescript/parameter-properties": "off",
	},
	overrides: [
		{
			files: ["*.test.ts"],
			plugins: ["vitest"],
			env: { node: true },
			rules: {
				"no-empty-pattern": "off",

				"vitest/require-hook": [
					"warn",
					{ allowedFunctionCalls: ["bundleIt", "fileIt"] },
				],
				"vitest/no-standalone-expect": [
					"warn",
					{ additionalTestBlockFunctions: ["bundleIt", "fileIt"] },
				],

				"vitest/no-importing-vitest-globals": "off",
				"vitest/no-hooks": "off",
				"vitest/prefer-lowercase-title": "off",
				"vitest/prefer-expect-assertions": "off",
				"vitest/prefer-to-be-truthy": "off",
				"vitest/prefer-to-be-falsy": "off",
				"vitest/prefer-called-times": "off",
				"vitest/expect-expect": "warn",
			},
		},
	],
});
